name: Checkmarx Scans

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  checkmarx:
    uses: retentionscience/checkmarx-gha-workflow/.github/workflows/checkmarx.yaml@main
    secrets: inherit
