name: Run Checkmarx

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, synchronize]
  repository_dispatch:
    types: [run-test-command]




jobs:
  test:
    name: Checkmarx
    runs-on: [self-hosted]
    concurrency:
      group: checkmarx
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.pull_request.head.sha }}

      - name: Remove unneeded files
        run: |
          rm -rf db spec script/data_migrations ./public/images/seconds_animated_60.gif test tests
          find . -name __tests__ -o -name __mocks__ -print0 | xargs -0 rm -rf

      - name: Verify environment
        run: |
          if [ "${{ secrets.CHECKMARX_TEAM }}" == '' ]; then echo "Error: CHECKMARX_TEAM was not set"; exit 1;fi

      - name: Checkmarx CxFlow Action
        uses: checkmarx-ts/checkmarx-cxflow-github-action@v1.5
        with:
          team: ${{ secrets.CHECKMARX_TEAM }}
          project: ${{ github.repository }}-PR
          checkmarx_url: ${{ secrets.CHECKMARX_URL }}
          checkmarx_client_secret: ${{ secrets.CHECKMARX_CLIENT_SECRET }}
          checkmarx_password: ${{ secrets.CHECKMARX_PASSWORD }}
          checkmarx_username: ${{ secrets.CHECKMARX_USERNAME }}
          sca_password: ${{ secrets.CHECKMARX_SCA_PASSWORD }}
          sca_username: ${{ secrets.CHECKMARX_SCA_USERNAME }}
          sca_tenant: ${{ secrets.CHECKMARX_SCA_TENANT }}
          incremental: false
          scanners: sast, sca
          break_build: true
          bug_tracker: GITHUBPULL
          params: --sca.team=${{ secrets.CHECKMARX_TEAM }} --namespace=${{ github.repository_owner }}  --repo-name=${{ github.event.repository.name }} --branch=${{ github.head_ref }} --merge-id=${{ github.event.number }} --cx-flow.filterSeverity --cx-flow.filterCategory
          java_opts: -Xmx4g
#--logging.level.com.checkmarx.flow.custom=debug --logging.level.com.checkmarx.flow.service=debug --logging.level.com.checkmarx.flow.utils=debug --logging.level.com.checkmarx.sdk.service=debug
# --github.threshold.high=0 --github.threshold.medium=0 --github.threshold.low=0
