name: Deploy

on:
  push:

jobs:
  deploy:
    name: Deploy
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install serverless
        run: npm install
      - name: serverless deploy to environment
        run: ./node_modules/serverless/bin/serverless.js deploy -s common
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
